### ISSUE TITLE
Default behavior does not match explicit hasHeader: true

### ISSUE THREAD

**Issue by AnikG** [vprince001/csv_to_json#1]
The README says

Use `hasHeader` key to specify if your file or data contains a header line or not.<br>
`Default is true and first line will be taken has header line`
```javascript
const dataInJSON = csvToJSON({ filePath: "./filePath.txt", hasHeader: true });
```

If hasHeader is set to true, the 1st line is not treated as data.  
If hasHeader is not specified, the README says the default behavior should be the same, but it is not.  In this case, the 1st line **is** treated as data.

Should I submit a PR?

**Comment by vprince001** [comment]
Hi @AnikG, Thank you for opening this issue. I would definitely appreciate your contribution but for now this issue has been fixed. Please use the latest version and this should be working as expected.
